#ifndef MAESTRO_PCA_H
#define MAESTRO_PCA_H
/* =====================================================================
   MaestroPCA — a servo sequencer for the PCA9685 that speaks Maestro.
   Part of the R2-D2 Simulator project.

   The Maestro is a servo co-processor: the sketch says restartScript(n)
   and the board runs the whole choreography by itself. The PCA9685 is a
   £5 PWM chip with no brain. This is the brain — and it keeps the
   Maestro's INTERFACE (so a Padawan sketch needs no changes) while
   deliberately going past its BEHAVIOUR where a droid benefits:

     · several sequences at once, on disjoint channels
     · looping sequences, and background ones that resume by themselves
     · oscillator and wander tracks — smooth sweeps and idle life that
       cost bytes instead of frames, and cannot be truncated
     · per-channel release-when-settled, so parked panels stop buzzing,
       stop drawing current and stop getting hot
     · per-channel easing, including overshoot-and-settle

   Drop-in conversion from PololuMaestro:
       MiniMaestro maestro(Serial3);          // before
       Adafruit_PWMServoDriver pca(0x40);     // after ─┐
       MaestroPCA maestro(&pca, 1, ...);      //        ├─ see examples/
       maestro.update();                      // once per loop()  ─┘
   Targets are QUARTER-MICROSECONDS (6000 = 1500 µs), exactly like the
   Maestro, so tuned endpoints from a .mstr carry over unchanged.

   Sequence data (sequences.h) is generated by the R2-D2 Simulator or by
   PCA Studio, from a Maestro settings file or from their own sequencer.

   Motion model (Maestro units):
     speed        0.25 µs per 10 ms      (0 = unlimited)
     acceleration 0.25 µs per 10 ms per 80 ms   (0 = unlimited)
   A 10 ms kinematics tick with a trapezoidal profile that never
   overshoots. A channel with no position yet snaps to its first target,
   because nothing can know where an undriven servo is.

   NOT interrupt-driven: update() must be called from loop(). Any delay()
   in the sketch freezes the animation for its duration.
   ===================================================================== */

#include <Arduino.h>
#include <Adafruit_PWMServoDriver.h>

/* ---- per-channel easing (the `ease` field below) ---- */
#define MPCA_EASE_NONE      0   /* trapezoid — speed/accel only          */
#define MPCA_EASE_SOFT      1   /* jerk-limited: acceleration itself
                                   ramps in, so the move breathes into
                                   motion instead of stepping into it    */
#define MPCA_EASE_OVERSHOOT 2   /* aim a little past, then settle back —
                                   reads as weight rather than machinery */

/* One row per channel. Generated tables live in PROGMEM.
   Fields were APPENDED over time on purpose: a header generated by an
   older version simply zero-fills the newer ones, which are all
   "behave as before" defaults. */
typedef struct {
  uint8_t  board;      /* index into the PCA9685 array (0 = first board)   */
  uint8_t  pin;        /* 0..15 on that board; 255 = channel unused        */
  uint16_t min;        /* quarter-µs endpoint — from YOUR calibration      */
  uint16_t max;        /* quarter-µs endpoint                              */
  uint16_t home;       /* quarter-µs startup pose; 0 = homemode Off (limp) */
  uint16_t speed;      /* 0.25 µs / 10 ms; 0 = unlimited                   */
  uint8_t  accel;      /* 0.25 µs / 10 ms / 80 ms; 0 = unlimited           */
  uint16_t releaseMs;  /* stop pulsing this many ms after arriving.
                          0 = hold forever (a real Maestro's only mode).
                          ONLY safe where the part rests in place on its
                          own — a servo holding against gravity will drop. */
  uint8_t  ease;       /* MPCA_EASE_*                                      */
} MpcaChannelDef;

/* ---- sequence flags ---- */
#define MPCA_SEQ_LOOP       0x01  /* repeat until stopped or displaced     */
#define MPCA_SEQ_BACKGROUND 0x02  /* if displaced, resume once the channels
                                     are free again — idle behaviour that
                                     survives being interrupted           */
#define MPCA_SEQ_OSC        0x04  /* data is oscillator entries, not frames */
#define MPCA_SEQ_WANDER     0x08  /* data is wander entries, not frames     */
#define MPCA_SEQ_GENERATOR  (MPCA_SEQ_OSC | MPCA_SEQ_WANDER)
/* v1.66.0 — the rows carry a SPEED per channel as well as a target, and
   the stride doubles to (1 + 2*channels). See the layout note below.

   Why it exists: the app compiles a ramp as a run of frames, and a frame
   commands its targets and then waits its duration. Without a speed the
   horn is chased flat out and arrives early, so a ramp is a stack of
   lunges; with the speed that FILLS the frame it crosses at a steady rate.
   The sim measured a velocity-ripple CV of 1.33 against 0.24 for the same
   routine at a 500 ms step.

   A header generated WITHOUT this flag is unchanged in every way, so an
   older sequences.h keeps working untouched. The dangerous direction is
   the other one — a NEWER header against an older copy of this library
   would read a doubled stride with the single-stride arithmetic and drive
   the wrong channels to garbage. The generator therefore emits a
   compile-time guard on this very symbol; do not rename it without
   changing maestro/pca-gen.js to match. */
#define MPCA_SEQ_SPEEDS     0x10

/* A normal sequence is a flat PROGMEM uint16_t array, stride (1+channels):
     durationMs, target_ch0 .. target_chN-1,  durationMs, targets...
   A target of 0 means "this frame does not drive this channel" — the
   Maestro sequencer convention, NOT "go to zero".

   With MPCA_SEQ_SPEEDS the stride is (1 + 2*channels) and each row is
     durationMs, target_ch0..chN-1, speed_ch0..speed_chN-1
   where a speed of 0 means "leave this channel's configured speed alone"
   (the same do-nothing convention as a 0 target) and MPCA_SPEED_FREE means
   "unlimited for this move", which 0 cannot say because 0 is already taken.
   A speed set by a frame is the ROUTINE's, not the channel's: it is put
   back from the channel table the moment the track lets the channel go,
   or a finished routine would leave the droid running at whatever pace
   its last frame happened to need.

   An OSC or WANDER sequence instead holds `count` entries of 5 words:
     channel, lo, hi, periodMs, phase(0..359)
   OSC eases smoothly lo → hi → lo every periodMs (zero velocity at each
   end, so it never jerks at the turn) and drives position directly, so
   it cannot be truncated by a frame that is too short — the trap the
   frame-based equivalent falls into. WANDER instead picks a fresh random
   target within lo..hi every periodMs and lets the channel's own
   speed/acceleration carry it there, which is what reads as idle life.
   Both run until stopped or displaced. `phase` offsets one entry against
   another, so a pan and a tilt need not swing together. */
#define MPCA_SPEED_FREE 0xFFFF   /* a frame asking for "no limit", since 0 means "unchanged" */

typedef struct {
  const uint16_t* data;
  uint16_t frameCount;   /* frames, or generator entries */
  uint8_t  flags;
} MpcaSeqDef;

/* How many sequences may run AT ONCE. Sequences that drive disjoint
   channels play together; one that claims a channel another is using
   displaces it (and if that one was BACKGROUND, it comes back later).
   ~14 bytes of RAM per track. */
#ifndef MPCA_MAX_TRACKS
#define MPCA_MAX_TRACKS 4
#endif

/* =====================================================================
   THE OUTPUT — where positions actually go

   The engine spent its first version talking to an array of
   Adafruit_PWMServoDriver*, which is a PCA9685 and nothing else. Nothing
   above this line is about a PCA9685: the sequences, the kinematics, the
   easing and the Maestro protocol are all just "put this channel at this
   many quarter-microseconds". So that is the whole interface, and a
   different board is a different subclass rather than a different engine.

   `code()` is the one part that is not obviously necessary, and it earns
   its place: a PCA9685 quantises to 4.88 µs steps at 50 Hz, so dozens of
   distinct quarter-µs targets land on the same tick. Deduping on the
   VALUE THAT GOES ON THE WIRE rather than on the target is what stops the
   engine hammering the I2C bus 100 times a second with a write that
   changes nothing. A backend with finer resolution simply returns the
   µs — it costs one integer call and buys the same protection.

   It takes `board` and `pin` because MpcaSplitOutput proved it had to: a
   rig whose channels are split across two different kinds of output
   quantises differently per bank, and a signature without the channel
   cannot say so. That is the shape being wrong the first time, corrected
   by the first thing that used it in anger.

   `board` and `pin` come straight from the channel table. On a PCA9685
   they mean what they say. On a board driving pins directly they are
   whatever identifies an output there — a generated table for such a
   board would put the real pin number in `pin` and leave `board` at 0.
   ===================================================================== */
class MpcaOutput {
public:
  virtual ~MpcaOutput() {}
  /* oscillatorHz is a PCA9685 trim and meaningless elsewhere; servoHz is
     the pulse rate, which every backend has an opinion about. */
  virtual void     begin(uint32_t oscillatorHz, float servoHz) = 0;
  virtual uint16_t code(uint8_t board, uint8_t pin, uint16_t qus) const = 0;
  virtual void     writeCode(uint8_t board, uint8_t pin, uint16_t code) = 0;
  virtual void     off(uint8_t board, uint8_t pin) = 0;
};

/* The PCA9685 backend — what this library has always done, now behind the
   interface rather than welded to the engine. */
class MpcaPca9685Output : public MpcaOutput {
public:
  MpcaPca9685Output(Adafruit_PWMServoDriver* const* boards, uint8_t boardCount)
    : _boards(boards), _count(boardCount), _usPerPeriod(20000UL) {}
  void     begin(uint32_t oscillatorHz, float servoHz) override;
  uint16_t code(uint8_t board, uint8_t pin, uint16_t qus) const override;
  void     writeCode(uint8_t board, uint8_t pin, uint16_t ticks) override;
  void     off(uint8_t board, uint8_t pin) override;
private:
  Adafruit_PWMServoDriver* const* _boards;
  uint8_t  _count;
  uint32_t _usPerPeriod;
};

/* =====================================================================
   MpcaSplitOutput — some channels here, the rest on another board

   The first `board` numbers go to a LOCAL output; anything above goes down
   a serial link to a second microcontroller that does nothing but make
   pulses. The channel table needs no change at all: it already says which
   board every channel is on, and nothing ever promised that a "board" was
   a PCA9685.

   The wire format is PCA Studio's, unchanged — three bytes, high bit
   marking the header so a dropped byte self-resyncs:

       byte0   0x80 | channel   (channel = board*16 + pin, 0..127)
       byte1   qus >> 7
       byte2   qus & 0x7F

   QUARTER-MICROSECONDS go over the wire, not the local output's codes.
   The far end quantises for its own hardware, which is the only place that
   knows how — and it is why `code()` takes the channel: local channels
   dedupe on the local quantisation, remote ones on the µs.

   WHEN THIS IS THE RIGHT ANSWER, and it is a narrow case: not to get past
   16 channels — two PCA9685s do that for the same money with no firmware
   and no protocol. It is for DISTANCE. I2C is a short, capacitance-shy bus
   and a droid has a slip ring in the middle of it; a UART tolerates a long
   noisy run far better. If the body bank is at the far end of the loom,
   this is the fix.
   ===================================================================== */
class MpcaSplitOutput : public MpcaOutput {
public:
  /* boards 0..localBoards-1 are `local`; the rest go down `link` */
  MpcaSplitOutput(MpcaOutput& local, uint8_t localBoards, Stream& link)
    : _local(local), _localBoards(localBoards), _link(link), _sent(0) {}
  void     begin(uint32_t oscillatorHz, float servoHz) override;
  uint16_t code(uint8_t board, uint8_t pin, uint16_t qus) const override;
  void     writeCode(uint8_t board, uint8_t pin, uint16_t code) override;
  void     off(uint8_t board, uint8_t pin) override;
  uint32_t framesSent() const { return _sent; }   /* is the link alive? */
private:
  void     frame(uint8_t board, uint8_t pin, uint16_t qus);
  MpcaOutput& _local;
  uint8_t  _localBoards;
  Stream&  _link;
  uint32_t _sent;
};

class MaestroPCA {
public:
  ~MaestroPCA();
  /* The original constructor, unchanged and still the one to use with
     PCA9685s — it wraps them in an MpcaPca9685Output for you, so every
     sketch and every generated sequences.h written before this existed
     compiles and behaves exactly as it did. */
  MaestroPCA(Adafruit_PWMServoDriver* const* boards, uint8_t boardCount,
             const MpcaChannelDef* channels, uint8_t channelCount,
             const MpcaSeqDef* sequences, uint8_t sequenceCount);

  /* Any other output: an ESP32 or Teensy driving pins directly, a test
     double, a serial bridge. The sequences, the editor and sequences.h
     are all unchanged — only this line is. */
  MaestroPCA(MpcaOutput& out,
             const MpcaChannelDef* channels, uint8_t channelCount,
             const MpcaSeqDef* sequences, uint8_t sequenceCount);

  /* Initialises each PCA9685 and applies each channel's home pose (or
     full-off for homemode Off). oscillatorHz trims the PCA9685's internal
     RC oscillator — boards vary a few percent, and until it is measured
     the quarter-µs endpoints are only nominal. */
  void begin(uint32_t oscillatorHz = 25000000UL, float servoHz = 50.0f);

  /* Call once per loop(). Steps the sequence players, the generators and
     the 10 ms kinematics ticks, and writes only what changed. */
  void update();

  /* ------ the Maestro-compatible surface ------ */
  void restartScript(uint8_t n);        /* displaces only overlapping ones */
  void stopScript();                    /* halt every track               */
  void setTarget(uint8_t ch, uint16_t targetQus);  /* quarter-µs; 0 = off */
  void setSpeed(uint8_t ch, uint16_t speed);
  void setAcceleration(uint8_t ch, uint8_t accel);
  uint8_t getMovingState();             /* 1 while anything is travelling */
  void setTargetMiniSSC(uint8_t ch, uint8_t v);

  /* ------ extras ------ */
  bool     scriptRunning() const;
  int8_t   currentScript() const;       /* most recently started, or -1   */
  bool     sequenceRunning(uint8_t n) const;
  void     stopSequence(uint8_t n);
  uint8_t  runningCount() const;
  uint16_t getPosition(uint8_t ch) const;   /* quarter-µs; 0 = not driven */
  bool     isReleased(uint8_t ch) const;    /* settled and gone quiet     */
  void     goHome();
  void     setRelease(uint8_t ch, uint16_t ms);   /* 0 = hold forever     */
  void     setEase(uint8_t ch, uint8_t ease);

private:
  struct ChanState {
    int32_t  pos256;    /* position, quarter-µs × 256 */
    int32_t  vel256;    /* velocity, quarter-µs-per-tick × 256, signed */
    uint16_t target;    /* what was asked for; 0 = off */
    uint16_t aim;       /* what we are actually driving at (overshoot) */
    uint16_t lo, hi;    /* the calibrated endpoints, cached from the table */
    uint16_t speed;
    uint8_t  accel;
    uint8_t  ease;
    uint16_t releaseMs;
    uint16_t settled;   /* ticks spent sitting on target */
    uint16_t launch;    /* ticks since this move began (MPCA_EASE_SOFT) */
    bool     active;    /* pulses being generated */
    bool     known;     /* we believe we know where the servo is, even if
                           released — so re-driving it eases rather than
                           snapping */
    uint16_t lastTicks; /* last value written to the PCA9685 */
    bool     seqSpeed;  /* a running sequence set this channel's speed, so it
                           has to be put back from the table when the track
                           releases it (v1.66.0) */
  };

  struct Track {
    int8_t   seq;
    int16_t  frame;
    uint32_t frameT;    /* ms into the frame, or ms since a generator began */
    uint32_t mask;
    uint32_t started;
  };

  MpcaOutput* _out;
  MpcaPca9685Output* _ownedOut;   /* non-null only for the PCA9685 ctor */
  const MpcaChannelDef* _table;
  uint8_t _count;
  const MpcaSeqDef* _seqs;
  uint8_t _seqCount;

  ChanState* _st;
  Track    _tk[MPCA_MAX_TRACKS];
  int8_t   _bgWait[MPCA_MAX_TRACKS];   /* displaced background sequences */
  uint32_t _startCount;
  uint32_t _lastMs;
  uint8_t  _tickAcc;
  uint32_t _rng;

  void     initCommon();
  void     applyFrame(uint8_t track, uint16_t f);
  uint32_t seqMask(uint8_t n) const;
  /* words per frame row — doubles when the sequence carries speeds */
  uint16_t seqStride(uint8_t flags) const {
    return (uint16_t)1 + ((flags & MPCA_SEQ_SPEEDS) ? (uint16_t)2*_count : (uint16_t)_count);
  }
  void releaseSeqSpeeds(uint32_t mask);
  void     bgRemember(uint8_t n);
  void     bgResume();
  void     stepChannel(uint8_t ch);
  void     driveChannel(uint8_t ch, uint16_t qus);   /* generators: set position */
  void     writeChannel(uint8_t ch);
  void     offChannel(uint8_t ch);
  uint16_t nextRandom(uint16_t lo, uint16_t hi);
  static uint32_t isqrt32(uint32_t v);
  static uint16_t smoothPingPong(uint32_t t, uint16_t period, uint16_t phaseDeg);
};

#endif
