'use strict';
/* =====================================================================
   BOARD ARTWORK — a picture of the thing on every hardware card

   Mike, 2026-08-16: "LEts add imaages of the COntrol borads ARdiunos /
   syren 10 / Flipsky ESC's / Hub motors PCA's DY-SV5W ect … these boxes
   should be the board images with a description underneith".

   The nine hardware questions were nine columns of prose. That is fine
   when you know what a Syren10 is and merely have to pick one — and no use
   at all when you are holding a board you bought from a forum post and
   trying to work out which of these words is it. A picture answers that in
   a glance, which is the whole job here; the note underneath is still what
   tells you what choosing it MEANS.

   ---------------------------------------------------------- two sources

   1 · A PHOTO, when there is one. `BOARD_PHOTOS` is generated by
       tools/build.js from whatever is sitting in `src/art/boards/`, inlined
       as a data URL so the single-file build keeps working off a memory
       stick. Drop `syren10.jpg` in that folder, run ./build.sh, done —
       no registration anywhere. Where an id is an answer to more than one
       question (mod2026 is dome, body AND firmware), `<step>-<id>` wins
       over the bare `<id>`.

       The four Pololu boards already have real, labelled photos in the
       app — js/app/board-img.js captured them for the wiring sheet — so
       they are wired straight through rather than waiting for a drop.

   2 · A DRAWING, otherwise. Hand-drawn SVG in the same idiom as
       config/model-art.js: one 120×72 box, one stroke weight, theme
       colours through `currentColor` and the CSS accents, about a
       kilobyte each. They are IDENTIFICATION, not renders — a PCA9685
       reads as a PCA9685 because it is a strip of sixteen three-pin
       headers, and a hub motor reads as a hub motor because it is a fat
       tyre round a hub. Nobody is fooled into thinking they are photos,
       which is the point: a photo is the promise "this is what yours looks
       like", and a drawing is "this is the KIND of thing".

   A card with neither gets no picture and lays out exactly as it did
   before — this is additive, and a build with an empty art folder is not a
   broken build.
   ===================================================================== */

/* the shared frame — everything draws inside this box, so the cards line up */
const BOARD_ART_VIEWBOX = '0 0 120 72';

/* ---------------------------------------------------------------- parts
   The vocabulary the drawings are built from, so twelve boards do not mean
   twelve hand-placed pin rows. `pins` draws a header strip; `screws` the
   mounting holes that make a PCB read as a PCB. */
function baPins(x, y, n, gap, len, cls){
  let s = '';
  for(let i=0;i<n;i++) s += '<line class="'+(cls||'ba-p')+'" x1="'+(x+i*gap)+'" y1="'+y+'" x2="'+(x+i*gap)+'" y2="'+(y+len)+'"/>';
  return s;
}
function baScrews(x0, y0, x1, y1){
  return [[x0,y0],[x1,y0],[x0,y1],[x1,y1]]
    .map(([x,y])=>'<circle class="ba-h" cx="'+x+'" cy="'+y+'" r="1.8"/>').join('');
}
function baBoard(x, y, w, h, cls){
  return '<rect class="'+(cls||'ba-b')+'" x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'" rx="2.5"/>';
}
function baChip(x, y, w, h){ return '<rect class="ba-c" x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'" rx="1"/>'; }
function baUsb(x, y, w, h){ return '<rect class="ba-m" x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'" rx="1"/>'; }
function baLabel(x, y, t){ return '<text class="ba-t" x="'+x+'" y="'+y+'" text-anchor="middle">'+t+'</text>'; }

/* ------------------------------------------------------------ the boards */

/* An Arduino, from above: the USB jack at one end, the barrel jack beside
   it, headers down both long edges. The Mega is drawn longer than the Uno
   because that IS the difference you see on a bench. */
function baArduino(long){
  const w = long ? 96 : 72, x = (120-w)/2;
  return baBoard(x, 16, w, 40)
    + baUsb(x-4, 22, 10, 11)
    + baUsb(x-4, 40, 8, 9)
    + baPins(x+14, 14, long ? 18 : 12, 4.2, 4)
    + baPins(x+14, 56, long ? 18 : 12, 4.2, 4)
    + baChip(x+w*0.42, 30, 22, 12)
    + baScrews(x+4, 20, x+w-4, 52);
}
/* The ADK's tell is the SECOND USB — the host socket, drawn in the accent
   because it is the whole reason this board is the recommended one. No
   caption: a word at this size fights the pin rows for the same pixels. */
function baArduinoAdk(){
  return baArduino(true)
    + '<rect class="ba-a" x="16" y="38" width="13" height="13" rx="1.5"/>'
    + '<path class="ba-a" d="M20 44 h5"/>';
}
function baEsp(){
  return baBoard(34, 14, 52, 44)
    + baUsb(30, 30, 8, 12)
    + baPins(38, 12, 10, 4.6, 4)
    + baPins(38, 58, 10, 4.6, 4)
    + '<rect class="ba-c" x="46" y="24" width="28" height="18" rx="1.5"/>'
    + '<path class="ba-a" d="M56 20 h8 M54 17 h12 M52 14 h16"/>';   /* the antenna zig */
}

/* A PCA9685: the long strip of sixteen three-pin servo headers is the
   entire silhouette, and it is unmistakable. */
function baPca(n){
  const boards = n || 1;
  let s = '';
  for(let b=0;b<boards;b++){
    const y = boards === 1 ? 22 : (10 + b*26);
    s += baBoard(10, y, 100, boards === 1 ? 28 : 22)
       + baPins(16, y+3, 16, 5.8, boards === 1 ? 22 : 16)
       + baChip(96, y+7, 9, 8);
  }
  return s;
}

/* A motor driver — Syren/Sabertooth: a heatsinked slab with screw
   terminals at one end and the DIP switch bank that everybody sets wrong. */
function baMotorDriver(big){
  return baBoard(14, 14, 92, 44)
    + '<path class="ba-d" d="M20 18 v36 M26 18 v36 M32 18 v36 M38 18 v36"/>'   /* heatsink fins */
    + '<rect class="ba-m" x="76" y="18" width="26" height="14" rx="1.5"/>'
    + '<rect class="ba-m" x="76" y="38" width="26" height="14" rx="1.5"/>'
    + baPins(50, 24, big ? 8 : 6, 4.4, 3, 'ba-a')
    + baLabel(60, 52, big ? '2x25' : '10A');
}

/* A brushless ESC: a potted brick with three fat phase wires out of one
   end and two power leads out of the other. */
function baEsc(){
  return baBoard(28, 18, 56, 36)
    + '<path class="ba-w" d="M28 26 C16 26 14 20 6 20 M28 36 C16 36 14 36 6 36 M28 46 C16 46 14 52 6 52"/>'
    + '<path class="ba-a" d="M84 30 C98 30 100 22 114 22 M84 42 C98 42 100 50 114 50"/>'
    + baChip(44, 28, 24, 16);
}
/* A hub motor: tyre, rim, hub, and the axle wire coming out of the middle. */
function baHubMotor(cx, r){
  const x = cx === undefined ? 60 : cx, R = r || 30;
  const k = R/30;
  return '<circle class="ba-b" cx="'+x+'" cy="36" r="'+R+'"/>'
    + '<circle class="ba-d" cx="'+x+'" cy="36" r="'+(22*k)+'"/>'
    + '<circle class="ba-c" cx="'+x+'" cy="36" r="'+(11*k)+'"/>'
    + '<circle class="ba-h" cx="'+x+'" cy="36" r="'+(3.5*k)+'"/>'
    + '<path class="ba-d" d="M'+x+' '+(36-R)+' v'+(8*k)+' M'+x+' '+(36+R-8*k)+' v'+(8*k)
    + ' M'+(x-R)+' 36 h'+(8*k)+' M'+(x+R-8*k)+' 36 h'+(8*k)+'"/>';
}
/* The foot-drive answer is a PAIR — "Flipsky FSESC + hub motors" — and the
   thing a builder is actually choosing is that pairing, so the card draws
   both: the ESC, the three phase wires, and the wheel on the end of them. */
function baEscHub(){
  return baBoard(8, 20, 44, 32)
    + baChip(18, 28, 24, 14)
    + '<path class="ba-a" d="M52 28 C64 28 62 22 74 22 M52 36 h20 M52 44 C64 44 62 50 74 50"/>'
    + baHubMotor(90, 24);
}
/* A sound module: a small board dominated by the microSD slot, with the
   speaker terminals at the other end. */
function baSound(){
  return baBoard(20, 16, 80, 40)
    + '<rect class="ba-m" x="26" y="22" width="30" height="18" rx="1.5"/>'
    + '<path class="ba-d" d="M30 26 h22 M30 30 h22 M30 34 h22"/>'
    + baChip(64, 24, 22, 14)
    + baPins(28, 46, 8, 5, 6, 'ba-a')
    + baScrews(24, 20, 96, 52);
}
/* The MP3Trigger is the odd one of the three sound boards: a bigger board
   with a row of screw terminals for its trigger inputs, which is what it is
   named for. Drawn apart from the other two so a card with a photo and two
   cards without do not read as "two of these are the same board". */
function baSoundTrigger(){
  return baBoard(14, 14, 92, 44)
    + '<rect class="ba-m" x="20" y="20" width="26" height="16" rx="1.5"/>'
    + '<path class="ba-d" d="M24 24 h18 M24 28 h18 M24 32 h18"/>'
    + baChip(56, 20, 20, 13)
    + '<rect class="ba-a" x="20" y="42" width="80" height="9" rx="1.5"/>'
    + baPins(26, 44, 9, 8.6, 5, 'ba-p')
    + baScrews(18, 18, 102, 50);
}

/* A NeoPixel/logic light board: a grid of LEDs is the whole idea. */
function baLights(grid){
  let s = baBoard(16, 18, 88, 36);
  if(grid){
    for(let r=0;r<3;r++) for(let c=0;c<9;c++)
      s += '<rect class="ba-a" x="'+(22+c*9)+'" y="'+(24+r*10)+'" width="6" height="6" rx="1"/>';
  }else{
    for(let c=0;c<7;c++) s += '<circle class="ba-a" cx="'+(26+c*12)+'" cy="36" r="4"/>';
  }
  return s;
}
/* A game pad, seen from above — two sticks, a d-pad, four buttons. */
function baPad(wireless){
  let s = '<path class="ba-b" d="M22 30 C22 20 34 18 44 22 L76 22 C86 18 98 20 98 30 '
        + 'C98 44 92 58 82 58 C74 58 72 50 60 50 C48 50 46 58 38 58 C28 58 22 44 22 30 Z"/>'
    + '<circle class="ba-d" cx="42" cy="40" r="7"/>'
    + '<circle class="ba-d" cx="78" cy="40" r="7"/>'
    + '<path class="ba-a" d="M52 30 h10 M57 25 v10"/>'
    + '<circle class="ba-a" cx="80" cy="26" r="2.6"/><circle class="ba-a" cx="86" cy="31" r="2.6"/>'
    + '<circle class="ba-a" cx="74" cy="31" r="2.6"/><circle class="ba-a" cx="80" cy="36" r="2.6"/>';
  if(wireless) s += '<path class="ba-a" d="M56 16 a10 10 0 0 1 8 0 M52 11 a18 18 0 0 1 16 0"/>';
  else s += '<path class="ba-w" d="M60 20 C60 12 50 10 44 6"/>';
  return s;
}
/* An RC transmitter: the box, two gimbals, the aerial. */
function baTx(){
  return baBoard(24, 20, 72, 40)
    + '<circle class="ba-d" cx="44" cy="40" r="9"/><circle class="ba-a" cx="44" cy="40" r="2.5"/>'
    + '<circle class="ba-d" cx="76" cy="40" r="9"/><circle class="ba-a" cx="76" cy="40" r="2.5"/>'
    + '<rect class="ba-m" x="52" y="24" width="16" height="10" rx="1.5"/>'
    + '<path class="ba-a" d="M30 20 V6"/>';
}
/* "none / not yet" — an empty outline, so the row still reads as a set */
function baBlank(){
  return '<rect class="ba-n" x="18" y="16" width="84" height="40" rx="3"/>'
    + '<path class="ba-n" d="M46 36 h28"/>';
}

/* ------------------------------------------------------- which is which
   Keyed by option id. `step` narrows the handful of ids that answer more
   than one question. */
const BOARD_ART = {
  /* controller */
  xbox360:  baPad.bind(null, true),
  xboxusb:  baPad.bind(null, false),
  rc:       baTx,
  /* controller board */
  megaadk:  baArduinoAdk,
  mega2560: baArduino.bind(null, true),
  due:      baArduino.bind(null, true),
  teensy:   baArduino.bind(null, false),
  esp32:    baEsp,
  nano:     baArduino.bind(null, false),
  uno:      baArduino.bind(null, false),
  mega:     baArduino.bind(null, true),
  other:    baBlank,
  /* servo hardware */
  mpca32:   baPca.bind(null, 2),
  mpca16:   baPca.bind(null, 1),
  mod2026:  baPca.bind(null, 1),
  pca:      baPca.bind(null, 1),
  /* dome motor / foot drive */
  syren10:          baMotorDriver.bind(null, false),
  sabertooth:       baMotorDriver.bind(null, true),
  sabertooth_dome:  baMotorDriver.bind(null, true),
  flipsky:          baEscHub,
  hub:              baHubMotor,
  esc:              baEsc,
  /* sound */
  dysv5w:   baSound,
  mdyx5300: baSound,
  mp3trigger: baSoundTrigger,
  /* dome lighting */
  astropixels: baLights.bind(null, false),
  teeces:      baLights.bind(null, true),
  none:        baBlank
};

/* The four Pololu boards have REAL photos already — captured for the
   wiring sheet (js/app/board-img.js). A card that could show the actual
   board should not show a drawing of one. */
function boardArtPololu(id){
  if(typeof BOARD_IMG === 'undefined') return '';
  const b = BOARD_IMG[id];
  return (typeof b === 'string') ? b : ((b && b.src) || '');
}

/* Questions whose answers are not OBJECTS. The firmware step's ids collide
   with hardware ones on purpose — `mod2026` is a sketch there and a PCA9685
   arrangement on the servo step — and a photo of a board on "which code
   will you flash?" is worse than no picture at all. */
const BOARD_ART_SKIP_STEPS = {firmware:1, env:1};

/* the photo for this answer, or '' */
function boardPhotoSrc(step, id){
  if(BOARD_ART_SKIP_STEPS[step]) return '';
  if(typeof BOARD_PHOTOS !== 'undefined' && BOARD_PHOTOS){
    /* the step-scoped name wins, so mod2026-the-dome-board and
       mod2026-the-sketch can be different pictures */
    if(step && BOARD_PHOTOS[step + '-' + id]) return BOARD_PHOTOS[step + '-' + id];
    if(BOARD_PHOTOS[id]) return BOARD_PHOTOS[id];
  }
  return boardArtPololu(id);
}

/* Is the picture a PHOTOGRAPH? The panel is dressed differently for one:
   Mike's shots (and Pololu's, and every product shot anyone will ever drop
   in that folder) are a board on a white studio background, so the panel
   goes WHITE behind them and the photo's own margins disappear into it.
   Letterboxing a white photo on a dark plate instead — which is what the
   first cut did — reads as a bright slab floating in a hole. */
function boardArtIsPhoto(step, id){ return !!boardPhotoSrc(step, id); }

/* Does this answer have a picture at all? Used by the card so a step with
   no art anywhere lays out exactly as it used to. */
function boardArtHas(step, id){
  if(BOARD_ART_SKIP_STEPS[step]) return false;
  return !!boardPhotoSrc(step, id) || !!BOARD_ART[id];
}

/* The markup: an <img> when there is a photo, an <svg> when there is not.
   `label` rides along as the alt text, because a picture of a board with
   no name is a rebus. */
function boardArtHtml(step, id, label){
  if(BOARD_ART_SKIP_STEPS[step]) return '';
  const esc = s=>String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
  const src = boardPhotoSrc(step, id);
  if(src) return '<img class="optphoto" src="'+src+'" alt="'+esc(label||id)+'" loading="lazy">';
  const draw = BOARD_ART[id];
  if(!draw) return '';
  return '<svg class="optart" viewBox="'+BOARD_ART_VIEWBOX+'" role="img" aria-label="'
    + esc(label||id) + '">' + draw() + '</svg>';
}
