'use strict';
/* =====================================================================
   MAESTRO — .mstr settings-file import / export and a sequence editor

   Schema and generator behaviour verified against Pololu's own SDK
   (pololu-usb-sdk → Maestro/Usc/ConfigurationFile.cs, Maestro/Sequencer/
   Sequence.cs, Frame.cs). All target values are quarter-microseconds:
   6000 = 1500 us = neutral.
   ===================================================================== */
/* ---------------------------------------------------------------- BOARDS
   Pololu ship four Maestros and they are NOT interchangeable in a settings
   file. The Micro is a different chip: it writes ServosAvailable/ServoPeriod
   where the Minis write MiniMaestroServoPeriod/ServoMultiplier, it has no
   input pull-ups, and its script space is 1 KB against the Minis' 8 KB —
   which is the limit you actually hit first when you copy sequences to the
   script. Channel counts and specs: pololu.com/category/102 and docs/0J40. */
const MAESTRO_BOARDS = [
  {id:'micro6', label:'Micro 6',  ch:6,  mini:false, script:1024, pullups:false,
   product:'Micro Maestro 6-Channel (#1350)',
   note:'One board for a small dome or a minimal body. 1 KB of script is tight — expect 2-3 sequences.'},
  {id:'mini12', label:'Mini 12',  ch:12, mini:true,  script:8192, pullups:true,
   product:'Mini Maestro 12-Channel (#1352)',
   note:'The common body board: four breadpan doors, both utility arms and the small hatches.'},
  {id:'mini18', label:'Mini 18',  ch:18, mini:true,  script:8192, pullups:true,
   product:'Mini Maestro 18-Channel (#1354)',
   note:'A body board with headroom, or a dome running 12 pies plus six side panels.'},
  {id:'mini24', label:'Mini 24',  ch:24, mini:true,  script:8192, pullups:true,
   product:'Mini Maestro 24-Channel (#1356)',
   note:'The usual dome board. Still two short of the MK4 dome’s 12 pies + 14 panels, so two panels stay fixed or go on a second board.'}
];
/* ------------------------------------------------------- the PCA route
   A PCA9685 is not a Maestro, but for the SEQUENCER it is the same kind of
   thing: a servo board with N channels that can be handed a stored routine
   and told to run it. Since v1.27.0 a mod2026-style build gets the same
   desk, and these pseudo-boards are how the editor knows how many channels
   it has. They are deliberately NOT in MAESTRO_BOARDS — that list is the
   Pololu board picker, and a PCA9685 is not something you pick there; it
   comes from the build's servo answers.

   `script: 0` means "no script space to run out of". The sequences live in
   PROGMEM on the co-processor instead, generated by pca-gen.js, so the
   limit you hit is flash on the Nano, which the header itself warns about
   past 128 sequences. Anything reading `script` must treat 0 as "not
   applicable" rather than "full". */
/* v1.54.0 — ONE TO EIGHT, generated rather than listed. There were two of
   these, `pca16` and `pca32`, because the live-drive wire protocol could not
   address more than two boards; it can address eight now, and Mike has three
   on the bench with a fourth planned ("for the dome I need two and one for
   the body - 4 pcas would future proof me"). The ids are the CHANNEL COUNT,
   which is why `pca16` and `pca32` keep their exact names and every saved
   build, workspace and exported file still reads. */
const PCA_MAX_BOARDS_UI = 8;      /* the wire protocol's ceiling — see serial-link.js */
const PCA_SEQ_BOARDS = [];
for(let n=1; n<=PCA_MAX_BOARDS_UI; n++){
  PCA_SEQ_BOARDS.push({
    id:'pca'+(n*16), label:'PCA9685'+(n>1?' ×'+n:''), ch:n*16,
    mini:true, script:0, pullups:false, pca:true, boards:n,
    product:(n===1 ? 'one PCA9685' : n+' PCA9685s')+' + a MaestroPCA co-processor',
    note:(n===1
       ? '16 channels on one £5 board. The co-processor runs the sequences, so the host sketch still just says restartScript(n).'
       : n===2
       ? '32 channels — the mod2026 arrangement, dome and body. Channel i lives on board i/16, pin i%16.'
       : (n*16)+' channels across '+n+' boards on one I2C bus. Channel i lives on board i/16, pin i%16; '
         + 'the addresses are found by a boot scan, so which jumpers you bridged does not matter.')
  });
}
/* the pseudo-board for n expanders — the one place that turns a COUNT into
   an id, so nobody has to know the ids are the channel count */
function pcaSeqBoardId(n){
  return 'pca' + (Math.max(1, Math.min(PCA_MAX_BOARDS_UI, n|0)) * 16);
}
function boardById(id){
  return MAESTRO_BOARDS.find(b=>b.id===id)
      || PCA_SEQ_BOARDS.find(b=>b.id===id)
      || MAESTRO_BOARDS[3];
}
/* "are these settings for a PCA9685 rather than a Pololu board?" — asked in
   enough places that guessing from the id twice would be a bug waiting */
function boardIsPca(id){ return !!boardById(id === undefined ? MSTR.board : id).pca; }
/* smallest board that will hold n channels */
function boardForCount(n){ return MAESTRO_BOARDS.find(b=>b.ch>=n) || MAESTRO_BOARDS[3]; }

const MSTR = {
  loaded:false, fileName:'', xmlText:'',
  /* `board` is which SERVO BOARD these settings describe — a Pololu id, or
     one of PCA_SEQ_BOARDS for the PCA9685 route. It has never meant "a
     Pololu board is plugged in", and boardIsPca() is how you ask. */
  board:'mini24',
  servoCount:24,
  /* {i,name,mode,min,max,home,homemode,neutral,range,speed,acceleration,act}
     — plus `invert`, RETIRED in v1.46.0. min is the shut end and max the open
     one, whatever their order; a legacy file's flag is adopted into that pair
     once and cleared. See chanNorm() in maestro/playback.js. */
  channels:[],
  sequences:[],       // {name, frames:[{name,duration,targets:[]}]}  — the LIBRARY
  loadout:null,       // ordered sequence names that go on the BOARD (null = all)
  subs:[],            // {index,name,kind:'sequence'|'frame'|'other',seqIndex,pushOrder}
  scriptText:'',
  header:{}           // preserved top-level settings
};
const EDIT = {
  active:false, view:'pose',
  seq:0, frame:-1,
  live:[],            // current pose, quarter-us per channel
  playing:null        // {i,t}
};

/* ------------------------------------------------------------- helpers */
const DEFAULT_MIN=4000, DEFAULT_MAX=8000, DEFAULT_NEUTRAL=6000;

/* ============================== WHERE A CHANNEL RESTS (v1.45.0)
   Mike: "Panels should be closed by default in the simulator; investigate the
   half-open Pi panels."

   They were half open because a channel with nothing measured into it rests at
   DEFAULT_NEUTRAL — mid-travel — and five separate places seeded the pose with
   `c.home || c.neutral || DEFAULT_NEUTRAL`. Mid-travel is the right answer for
   a gimbal and the WRONG answer for a door: a pie panel parked at 6000 is a
   pie panel standing half open, on the model, before anybody has touched it.
   `makeStarter()` already knew this (its mapped channels are created with
   `home:DEFAULT_MIN` precisely "so doors rest shut") — nothing else did.

   So the resting pose is a question about the ACTUATOR, not about the number:
     · a part on screen rests where ITS KIND rests — a door shut, a bipolar
       actuator (a holo pan/tilt, a head gimbal, a builder joint) centred —
       EVEN when the channel carries a measured Goto home. (2026-08-18,
       Mike: the panels on the model "are used for approximation not exact"
       — a user may home a real door slightly ajar to spare a linkage, and
       the model must not stand there ajar copying the number. Until then a
       stale stored starter with `home:6000, homemode:'Goto'` parked every
       mapped panel HALF OPEN, resurrecting the exact v1.45.0 bug.)
     · a board-only channel (no part on screen) obeys an explicit Goto home
       — somebody measured that, and there is nothing on the model to lie
   `homemode` Off/Ignore means the board does not drive the channel at power-up
   at all, so there is no number to obey and the actuator's own answer wins.
   One reader, `chanRest(c)`, in quarter-µs, so the model and the board agree. */
const ACT_CENTRED = /(pan|tilt|nod|spin|rot|wag)/i;
function actRestNorm(act){
  if(!act) return null;                 // board-only channel: nothing on screen to rest
  if(typeof anzIsAct === 'function' && anzIsAct(act) && typeof anzHome === 'function') return anzHome(act);
  if(typeof mbIsAct === 'function' && mbIsAct(act)) return 0.5;   // a builder joint is bipolar
  return ACT_CENTRED.test(act) ? 0.5 : 0;
}
function chanRest(c){
  if(!c) return DEFAULT_NEUTRAL;
  const r = actRestNorm(c.act);
  /* v1.46.0 — chanDenorm(), not a sorted pair: min is the SHUT end and max
     the open one whatever their numeric order, so "a door rests at 0" now
     parks a reversed channel at its own shut end rather than at whichever
     number happened to be lower. One rule, see chanNorm() in playback.js. */
  if(r !== null) return chanDenorm(c, r);
  if(/^goto$/i.test(c.homemode || '') && c.home !== undefined && c.home !== null) return c.home;
  return (c.home !== undefined && c.home !== null) ? c.home : (c.neutral || DEFAULT_NEUTRAL);
}

function qus(v){ return (v/4).toFixed(0)+' us'; }
function xmlEsc(s){ return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }
function niceName(s){ return String(s).replace(/\s+/g,'_').replace(/[^a-z0-9_]/gi,''); }

/* which droid part a channel name looks like */
const PART_LIST = [
  ['—','',''],
  ['Dome pie 1','pie0'],['Dome pie 2','pie1'],['Dome pie 3','pie2'],['Dome pie 4','pie3'],
  ['Dome pie 5','pie4'],['Dome pie 6','pie5'],['Dome pie 7','pie6'],['Dome pie 8','pie7'],
  ['Dome pie 9','pie8'],['Dome pie 10','pie9'],['Dome pie 11','pie10'],['Dome pie 12','pie11'],
  ['Upper utility arm','utilUp'],['Lower utility arm','utilLo'],
  ['Left body door','doorL'],['Right body door','doorR'],
  ['Gripper arm','gripArm'],['Gripper claw','claw'],
  ['Interface arm','interArm'],['Interface tool','interTool'],
  ['Dataport door','dataport'],['Chargebay door','chargebay'],
  ['Rear-left body door','doorRL'],['Rear-right body door','doorRR'],
  ['Small long door','smallDoor'],['Drawer','drawer'],
  /* HP1/HP2/HP3 — the dome holoprojectors, a pan/tilt pair each. Printed
     Droid names the axes HP1-1 / HP1-2 and real files are full of them. */
  ['Holoprojector 1 pan','hp1Pan'],['Holoprojector 1 tilt','hp1Tilt'],
  ['Holoprojector 2 pan','hp2Pan'],['Holoprojector 2 tilt','hp2Tilt'],
  ['Holoprojector 3 pan','hp3Pan'],['Holoprojector 3 tilt','hp3Tilt']
].concat(Array.from({length:14},(_,i)=>['Dome side panel '+(i+1),'panel'+i]))
 /* the Anzellan head's face rig — a second animatronic on the same bench,
    wired to its own board. See scene/anzellan.js. */
 .concat([
  ['Frik jaw','anzJaw'],['Frik upper lip','anzLipU'],['Frik lower lip','anzLipL'],
  ['Frik left brow','anzBrowL'],['Frik right brow','anzBrowR'],['Frik eyelids','anzLids'],
  ['Frik eyes pan','anzEyeX'],['Frik eyes tilt','anzEyeY'],
  ['Frik head pan','anzPan'],['Frik head tilt','anzTilt'],['Frik head nod','anzNod']
 ]);
function guessPart(name){
  const n = (name||'').toLowerCase();
  const num = ()=>{ const m=/(\d+)/.exec(n); return m?parseInt(m[1],10):0; };
  /* The Anzellan head goes FIRST, because its channel names carry words the
     droid rules also look for — "Frik lower lip" must not be read as a lower
     utility arm, and "Frik left brow" must not be read as a left door. */
  if(/frik|anzell|head\s*rig|puppet/.test(n)){
    if(/jaw|mouth/.test(n))              return 'anzJaw';
    if(/lip/.test(n))                    return /lower|bottom/.test(n) ? 'anzLipL' : 'anzLipU';
    if(/brow|eyebrow/.test(n))           return /right/.test(n) ? 'anzBrowR' : 'anzBrowL';
    if(/lid|blink/.test(n))              return 'anzLids';
    if(/eye/.test(n))                    return /tilt|up|vert/.test(n) ? 'anzEyeY' : 'anzEyeX';
    if(/nod|pitch/.test(n))              return 'anzNod';
    if(/tilt|roll/.test(n))              return 'anzTilt';
    if(/pan|turn|yaw/.test(n))           return 'anzPan';
  }
  // specific assemblies first — 'Utility Arm Panel' must not read as a side panel
  if(/upper/.test(n) && /util/.test(n)) return 'utilUp';
  if(/lower/.test(n) && /util/.test(n)) return 'utilLo';
  if(/grip/.test(n) && /(claw|hand|finger|jaw)/.test(n)) return 'claw';
  if(/grip/.test(n)) return 'gripArm';
  if(/interface|inter/.test(n) && /(tool|tip|spinner|probe)/.test(n)) return 'interTool';
  if(/interface|inter/.test(n)) return 'interArm';
  if(/data\s*_?port/.test(n)) return 'dataport';
  if(/charg/.test(n)) return 'chargebay';          // 'chargebay' and 'Charging Bay'
  if(/drawer/.test(n)) return 'drawer';
  if(/small/.test(n) && /long/.test(n)) return 'smallDoor';
  // MK4 names its four body doors FL / FR / RL / RR
  if(/\bfl\b|front[\s_-]*left/.test(n))  return 'doorL';
  if(/\bfr\b|front[\s_-]*right/.test(n)) return 'doorR';
  if(/\brl\b|rear[\s_-]*left/.test(n))   return 'doorRL';
  if(/\brr\b|rear[\s_-]*right/.test(n))  return 'doorRR';
  if(/left/.test(n) && /door/.test(n)) return 'doorL';
  if(/right/.test(n) && /door/.test(n)) return 'doorR';
  /* ---- Printed Droid shorthand -------------------------------------
     printed-droid.com/kb/r2-d2-terminology is what the community actually
     names channels, and it is nothing like the sim's own labels. Mike's
     real 18-channel dome file mapped 0 of 18 before these four rules:
       PP1..PP6   pie panels          (PP3 is usually HP3, PP4 the periscope)
       P1..P14    lower dome panels   ("P1-Fix" is still P1)
       HPn-1/-2   holoprojector n, axis 1 = pan, axis 2 = tilt
     Kept tight — anchored at the start and requiring the digit to follow the
     prefix immediately — so "Panel 3" and "Pie 2" fall through to the
     descriptive rules below and are not read as P-something. */
  let m;
  if((m = /^\s*hp\s*(\d+)\s*(?:[-_ ]\s*(\d+))?\b/.exec(n))){
    const unit = clamp(parseInt(m[1],10), 1, 3);
    const axis = m[2] ? parseInt(m[2],10) : 1;
    return 'hp'+unit+(axis >= 2 ? 'Tilt' : 'Pan');
  }
  if(/holo/.test(n)){
    const unit = clamp(num()||1, 1, 3);
    return 'hp'+unit+(/tilt|lift|up|vert/.test(n) ? 'Tilt' : 'Pan');
  }
  if((m = /^\s*pp\s*(\d+)/.exec(n)))  return 'pie'   + clamp(parseInt(m[1],10)-1, 0, PIE_COUNT-1);
  if((m = /^\s*p\s*(\d+)/.exec(n)))   return 'panel' + clamp(parseInt(m[1],10)-1, 0, PANEL_COUNT-1);
  // dome: pie panels vs side panels
  if(/\bpie\b|pie\s*\d/.test(n))  return 'pie'   + clamp(num()-1, 0, PIE_COUNT-1);
  if(/panel/.test(n))               return 'panel' + clamp(num()-1, 0, PANEL_COUNT-1);
  return '';
}
/* Which lower dome panels Printed Droid lists as NOT servo'd — they carry
   lights or displays. Used by the importer to query a surprising mapping
   rather than to refuse it: plenty of builds move something the reference
   drawing does not. */
const PD_NON_SERVO_PANELS = {5:'Magic Panel', 6:'small upper panel', 8:'Rear PSI',
                             9:'Rear Logic Display', 12:'Front Logic Displays', 14:'Front PSI'};
function pdPanelWarning(name){
  const m = /^\s*p\s*(\d+)/i.exec(String(name||'').toLowerCase());
  if(!m) return '';
  const n = parseInt(m[1],10);
  return PD_NON_SERVO_PANELS[n] ? ('P'+n+' is the '+PD_NON_SERVO_PANELS[n]+' on the Printed Droid reference — usually lighting, not a servo.') : '';
}
