'use strict';
/* ============================================================== PCA GEN
   Generates the sequences.h consumed by arduino/MaestroPCA — the cheap
   PCA9685 route for people who don't want to buy a Maestro. ONE generator,
   two front-ends:

     pcaGenFromLoadout()   the sim's own state: MSTR.channels verbatim +
                           the LOADOUT in order, so slot numbers match the
                           .mstr script this sim would export — the sketch
                           does not care which board it is talking to.
     pcaGenFromParsed(P)   a freshly parsed .mstr (mstrParse result). Slot
                           order follows the SCRIPT's sequence subroutines
                           when the file has a script — that is what
                           restartScript(n) actually addressed on the real
                           board — and falls back to <Sequences> order.

   The channel table is copied through VERBATIM (names, min, max, home,
   speed, acceleration): endpoints are personal calibration and this
   generator has no opinions about them.

   This file is SHARED with PCA Studio, which is built from it — the two
   tools must emit byte-identical headers from the same project, and a
   copy is not a guarantee. The sim-only front-ends live in pca-gen-sim.js
   because they read MSTR/LOADOUT, which Studio does not have.
   ===================================================================== */

function pcaCName(s){
  const t = String(s).toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_+|_+$/g,'');
  return t || 'SEQ';
}

/* board/pin assignment: channel i → PCA9685 (i>>4) pin (i&15). Non-servo
   channels keep their row (frame targets index by channel number) but get
   pin 255 = unused. */
function pcaGenHeader(channels, sequences, meta){
  const m = meta || {};
  const n = channels.length;
  const boards = Math.max(1, Math.ceil(n/16));
  const src = m.source || 'sim';
  let s = '';
  const ver = m.appVersion
    || (typeof APP_VERSION    !== 'undefined' ? APP_VERSION    : null)
    || (typeof STUDIO_VERSION !== 'undefined' ? STUDIO_VERSION : '?');
  s += '/* sequences.h — generated by the R2-D2 Simulator v'+ver+'\n';
  s += '   Source: '+src+' ('+n+' channels, '+sequences.length+' sequence'+(sequences.length===1?'':'s')+')\n';
  s += '   Consumed by the MaestroPCA library (arduino/MaestroPCA).\n';
  s += '\n';
  s += '   Wiring: channel i lives on PCA9685 board (i/16), pin (i%16).\n';
  /* v1.63.0 — this used to print "board 0 -> 0x40, board 1 -> 0x41" and so
     on, which stopped being true in v1.53.0 when the sketches started
     FINDING their boards instead of assuming consecutive addresses from
     0x40. Mike's own question is why they scan: "I and others may jumper
     them differently". A generated header that names addresses the boot
     scan may never use is worse than one that names none — somebody wires
     to the comment. So it says what decides it instead. */
  for(let b=0;b<boards;b++) s += '     board '+b+' -> channels '+(b*16)+'..'+Math.min(n-1,b*16+15)+'\n';
  s += '     Board numbers are ASCENDING I2C ADDRESS as found by the boot\n';
  s += '     scan (0x40-0x7F, All Call excluded) — bridge whichever jumpers\n';
  s += '     suit the build. The sketch prints the mapping it settled on.\n';
  s += '\n';
  s += '   MPCA_CHANNELS BELOW IS FIXED WHEN YOU FLASH THIS. A PCA9685 added\n';
  s += '   to the bus afterwards is found and woken, and live drive reaches\n';
  s += '   it, but no routine does — the sketch prints it as "spare". Add a\n';
  s += '   board, regenerate this file, re-flash.\n';
  s += '   Targets are QUARTER-MICROSECONDS (6000 = 1500 us), straight from\n';
  s += '   the Maestro channel table — endpoints are YOUR calibration.\n';
  s += '   Calibrate the PCA9685 oscillator (maestro.begin(<hz>)) or these\n';
  s += '   values are only nominal on the wire. */\n';
  s += '#pragma once\n#include <MaestroPCA.h>\n\n';
  s += '#define MPCA_CHANNELS  '+n+'\n';
  s += '#define MPCA_SEQUENCES '+sequences.length+'\n';
  /* Pololu's restartScript() sends the subroutine number as 7-BIT data
     (write7BitData masks with 0x7F), so over the serial link slot 130
     would silently fire slot 2. Direct API calls are fine to 255. */
  if(sequences.length > 128)
    s += '#warning More than 128 sequences: over the Maestro serial protocol the\n'
       + '// subroutine number is 7-bit, so slots above 127 wrap (130 -> 2).\n'
       + '// Direct restartScript() calls on this board are unaffected.\n';
  s += '\n';

  s += '/* releaseMs: stop pulsing this long after arriving — a parked panel\n';
  s += '   then draws nothing and makes no noise. ONLY safe where the part\n';
  s += '   rests in place on its own; a servo holding against gravity drops.\n';
  s += '   0 = hold forever, which is a real Maestro\'s only behaviour. */\n';
  s += '/*  board pin    min    max   home  speed accel  release  ease */\n';
  s += 'const MpcaChannelDef MPCA_CHANNEL_TABLE[MPCA_CHANNELS] PROGMEM = {\n';
  const EASE = {soft:'MPCA_EASE_SOFT', overshoot:'MPCA_EASE_OVERSHOOT'};
  channels.forEach((c,i)=>{
    const servo = /^servo/i.test(c.mode||'Servo');
    const home = servo ? (/off|ignore/i.test(c.homemode||'') ? 0 : (c.home|0)) : 0;
    const pad = (v,w)=>String(v).padStart(w);
    const ease = servo ? (EASE[c.ease] || 'MPCA_EASE_NONE') : 'MPCA_EASE_NONE';
    s += '  { '+pad(i>>4,2)+', '+pad(servo? (i&15):255,3)+', '+pad(servo?c.min|0:0,5)+', '+pad(servo?c.max|0:0,5)+', '
       + pad(home,5)+', '+pad(servo?c.speed|0:0,4)+', '+pad(servo?c.acceleration|0:0,4)+', '
       + pad(servo?c.releaseMs|0:0,7)+', '+ease.padEnd(19)+' },'
       + '   /* ch'+String(i).padStart(2)+' '+(c.name||'')+(servo?'':' — '+(c.mode||'')+', unused')+' */\n';
  });
  s += '};\n\n';

  s += '/* Frame stride = 1 duration + '+n+' targets. 0 = channel not driven\n';
  s += '   by that frame (the Maestro sequencer convention).\n';
  s += '   Sequences on disjoint channels play AT THE SAME TIME; one that\n';
  s += '   claims a channel another is using displaces it. MPCA_SEQ_LOOP\n';
  s += '   repeats until stopped or displaced. */\n';
  const seqNames = [];
  const isGen = q => q.gen === 'osc' || q.gen === 'wander';
  sequences.forEach((seq,k)=>{
    if(isGen(seq)){
      s += 'static const uint16_t MPCA_SEQ'+k+'[] PROGMEM = {   /* '+seq.name
         + ' — '+(seq.gen==='osc'?'oscillator':'wander')+' */\n';
      s += '  /* ch, lo, hi, periodMs, phase */\n';
      (seq.entries||[]).forEach(g=>{
        s += '  '+String(g.ch|0).padStart(3)+', '+String(g.lo|0).padStart(5)+', '
           + String(g.hi|0).padStart(5)+', '+String(g.period|0).padStart(6)+', '
           + String(g.phase|0).padStart(4)+',\n';
      });
      s += '};\n';
      seqNames.push(seq.name);
      return;
    }
    s += 'static const uint16_t MPCA_SEQ'+k+'[] PROGMEM = {   /* '+seq.name+' */\n';
    seq.frames.forEach(fr=>{
      const dur = Math.max(0, Math.min(65535, fr.duration|0));
      const tg = [];
      for(let c=0;c<n;c++) tg.push(Math.max(0, Math.min(65535, fr.targets[c]|0)));
      s += '  '+String(dur).padStart(5)+', '+tg.join(', ')+',\n';
    });
    s += '};\n';
    seqNames.push(seq.name);
  });
  s += '\nconst MpcaSeqDef MPCA_SEQ_TABLE[MPCA_SEQUENCES] PROGMEM = {\n';
  sequences.forEach((seq,k)=>{
    const f = [];
    if(seq.loop) f.push('MPCA_SEQ_LOOP');
    if(seq.background) f.push('MPCA_SEQ_BACKGROUND');
    if(seq.gen === 'osc') f.push('MPCA_SEQ_OSC');
    if(seq.gen === 'wander') f.push('MPCA_SEQ_WANDER');
    const count = isGen(seq) ? (seq.entries||[]).length : seq.frames.length;
    const note = [seq.gen === 'osc' ? 'sweeps' : null,
                  seq.gen === 'wander' ? 'wanders' : null,
                  (seq.loop && !isGen(seq)) ? 'loops' : null,
                  seq.background ? 'background — resumes when its channels free up' : null
                 ].filter(Boolean).join(', ');
    s += '  { MPCA_SEQ'+k+', '+count+', '+(f.length?f.join(' | '):'0')+' },'
       + '   /* '+k+': '+seq.name+(note?' ('+note+')':'')+' */\n';
  });
  s += '};\n\n';

  /* slot defines — restartScript(MPCA_SLOT_...) reads better than a bare n */
  const used = {};
  seqNames.forEach((nm,k)=>{
    let id = 'MPCA_SLOT_'+pcaCName(nm);
    while(used[id]) id += '_';
    used[id] = true;
    s += '#define '+id+' '+k+'\n';
  });
  /* v1.48.0 — the bricks ride along as a comment the compiler ignores, so
     importing this file back gives EDITABLE routines when the endpoints
     still agree (blocksPack()/blocksTryAttach(), maestro/blocks.js).
     base64: `* /` cannot occur, so the comment cannot end early. */
  const packed = (typeof blocksPack === 'function') ? blocksPack(sequences) : '';
  if(packed) s += '\n/* r2sim:blocks '+packed+' */\n';
  /* v1.48.1 — and the part mapping, for the same reason and by the same
     means: a MaestroPCA table has no column for "which panel", so without
     this a wholesale import re-derives it with guessPart(name) and re-wires
     a droid whose channel names disagree with the CAD's numbering
     (export.js mstrActsComment carries the whole argument). */
  const packedActs = (typeof actsPack === 'function') ? actsPack(channels) : '';
  if(packedActs) s += '\n/* r2sim:acts '+packedActs+' */\n';
  return s;
}
