/* sequences.h — generated by the R2-D2 Simulator v1.24.0
   Source: R2-dome-padawan.mstr (18 channels, 8 sequences)
   Consumed by the MaestroPCA library (arduino/MaestroPCA).

   Wiring: channel i lives on PCA9685 board (i/16), pin (i%16).
     board 0 -> I2C address 0x40 (channels 0..15)
     board 1 -> I2C address 0x41 (channels 16..17)
   Targets are QUARTER-MICROSECONDS (6000 = 1500 us), straight from
   the Maestro channel table — endpoints are YOUR calibration.
   Calibrate the PCA9685 oscillator (maestro.begin(<hz>)) or these
   values are only nominal on the wire. */
#pragma once
#include "MaestroPCA.h"

#define MPCA_CHANNELS  18
#define MPCA_SEQUENCES 8

/*  board pin    min    max   home  speed accel */
const MpcaChannelDef MPCA_CHANNEL_TABLE[MPCA_CHANNELS] PROGMEM = {
  {  0,   0,  4544,  7296,     0,   80,   10 },   /* ch 0 PP5 */
  {  0,   1,  4544,  7296,     0,   80,   10 },   /* ch 1 PP6 */
  {  0,   2,  5056,  7744,     0,   80,   10 },   /* ch 2 PP1 */
  {  0,   3,  4544,  7296,     0,   80,   10 },   /* ch 3 PP2 */
  {  0,   4,  3968,  8000,     0,   80,   10 },   /* ch 4 HP3-1 */
  {  0,   5,  3968,  8000,     0,   80,   10 },   /* ch 5 HP3-2 */
  {  0,   6,  4032,  7616,     0,   80,   10 },   /* ch 6 P13 */
  {  0,   7,  3968,  8000,     0,   80,   10 },   /* ch 7 HP1-1 */
  {  0,   8,  3968,  8000,     0,   80,   10 },   /* ch 8 HP1-2 */
  {  0,   9,  3968,  8000,     0,   80,   10 },   /* ch 9 P1-Fix */
  {  0,  10,  4032,  7616,     0,   80,   10 },   /* ch10 P2 */
  {  0,  11,  4032,  7360,     0,   80,   10 },   /* ch11 P3 */
  {  0,  12,  3968,  7616,     0,   80,   10 },   /* ch12 P4 */
  {  0,  13,  4416,  8000,     0,   80,   10 },   /* ch13 P7 */
  {  0,  14,  3776,  8000,     0,   80,   10 },   /* ch14 HP2-1 */
  {  0,  15,  3968,  8000,     0,   80,   10 },   /* ch15 HP2-2 */
  {  1,   0,  4416,  7744,     0,   80,   10 },   /* ch16 P11 */
  {  1,   1,  3968,  8000,     0,   80,   10 },   /* ch17 Channel 17 */
};

/* Frame stride = 1 duration + 18 targets. 0 = channel not driven
   by that frame (the Maestro sequencer convention).
   Sequences on disjoint channels play AT THE SAME TIME; one that
   claims a channel another is using displaces it. MPCA_SEQ_LOOP
   repeats until stopped or displaced. */
static const uint16_t MPCA_SEQ0[] PROGMEM = {   /* Dome Pies Open */
    400, 0, 0, 7744, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    400, 0, 0, 0, 7296, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    400, 7296, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    400, 0, 7296, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};
static const uint16_t MPCA_SEQ1[] PROGMEM = {   /* Dome Pies Close */
    400, 0, 4544, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    400, 4544, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    400, 0, 0, 0, 4544, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    400, 0, 0, 5056, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};
static const uint16_t MPCA_SEQ2[] PROGMEM = {   /* Dome Panels Open */
    380, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8000, 0, 0, 0, 0, 0, 0, 0, 0,
    380, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7616, 0, 0, 0, 0, 0, 0, 0,
    380, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7360, 0, 0, 0, 0, 0, 0,
    380, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7616, 0, 0, 0, 0, 0,
    380, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8000, 0, 0, 0, 0,
    380, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7744, 0,
    380, 0, 0, 0, 0, 0, 0, 7616, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};
static const uint16_t MPCA_SEQ3[] PROGMEM = {   /* Dome Panels Close */
    380, 0, 0, 0, 0, 0, 0, 4032, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    380, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4416, 0,
    380, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4416, 0, 0, 0, 0,
    380, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3968, 0, 0, 0, 0, 0,
    380, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4032, 0, 0, 0, 0, 0, 0,
    380, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4032, 0, 0, 0, 0, 0, 0, 0,
    380, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3968, 0, 0, 0, 0, 0, 0, 0, 0,
};
static const uint16_t MPCA_SEQ4[] PROGMEM = {   /* Whole Dome Open */
    500, 7296, 7296, 7744, 7296, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   1200, 0, 0, 0, 0, 0, 0, 7616, 0, 0, 8000, 7616, 7360, 7616, 8000, 0, 0, 7744, 0,
};
static const uint16_t MPCA_SEQ5[] PROGMEM = {   /* Whole Dome Close */
    500, 0, 0, 0, 0, 0, 0, 4032, 0, 0, 3968, 4032, 4032, 3968, 4416, 0, 0, 4416, 0,
   1200, 4544, 4544, 5056, 4544, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};
static const uint16_t MPCA_SEQ6[] PROGMEM = {   /* Dome Wave */
    400, 0, 0, 7744, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    400, 0, 0, 0, 7296, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    400, 7296, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    400, 0, 7296, 5056, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    400, 0, 0, 0, 4544, 0, 0, 0, 0, 0, 8000, 0, 0, 0, 0, 0, 0, 0, 0,
    400, 4544, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7616, 0, 0, 0, 0, 0, 0, 0,
    400, 0, 4544, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7360, 0, 0, 0, 0, 0, 0,
    400, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3968, 0, 0, 7616, 0, 0, 0, 0, 0,
    400, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4032, 0, 0, 8000, 0, 0, 0, 0,
    400, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4032, 0, 0, 0, 0, 7744, 0,
    400, 0, 0, 0, 0, 0, 0, 7616, 0, 0, 0, 0, 0, 3968, 0, 0, 0, 0, 0,
    400, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4416, 0, 0, 0, 0,
    400, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4416, 0,
    400, 0, 0, 0, 0, 0, 0, 4032, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};
static const uint16_t MPCA_SEQ7[] PROGMEM = {   /* Dome Home */
   1200, 4544, 4544, 5056, 4544, 5984, 5984, 4032, 5984, 5984, 3968, 4032, 4032, 3968, 4416, 5888, 5984, 4416, 0,
};

const MpcaSeqDef MPCA_SEQ_TABLE[MPCA_SEQUENCES] PROGMEM = {
  { MPCA_SEQ0, 4, 0 },   /* 0: Dome Pies Open */
  { MPCA_SEQ1, 4, 0 },   /* 1: Dome Pies Close */
  { MPCA_SEQ2, 7, 0 },   /* 2: Dome Panels Open */
  { MPCA_SEQ3, 7, 0 },   /* 3: Dome Panels Close */
  { MPCA_SEQ4, 2, 0 },   /* 4: Whole Dome Open */
  { MPCA_SEQ5, 2, 0 },   /* 5: Whole Dome Close */
  { MPCA_SEQ6, 14, 0 },   /* 6: Dome Wave */
  { MPCA_SEQ7, 1, 0 },   /* 7: Dome Home */
};

#define MPCA_SLOT_DOME_PIES_OPEN 0
#define MPCA_SLOT_DOME_PIES_CLOSE 1
#define MPCA_SLOT_DOME_PANELS_OPEN 2
#define MPCA_SLOT_DOME_PANELS_CLOSE 3
#define MPCA_SLOT_WHOLE_DOME_OPEN 4
#define MPCA_SLOT_WHOLE_DOME_CLOSE 5
#define MPCA_SLOT_DOME_WAVE 6
#define MPCA_SLOT_DOME_HOME 7
