#!/usr/bin/env node
/* Generates pca-studio/PCA-Studio.html from pca-studio/manifest.json.
 *
 * Studio stays ONE self-contained file you open from disk — that has always
 * been the point of it — but it is no longer a file you hand-edit. It used
 * to carry its own copy of the engine and the sequences.h generator, kept
 * byte-compatible with the sim's by hand. That worked right up until it
 * didn't: the endpoint-clamp fix of v1.25.1 landed in two of the three
 * copies before anyone noticed the third. Shared modules are listed in the
 * manifest by their real path under src/, so there is nothing to keep in
 * step.
 *
 * Unlike the sim there is no dev build: Studio is small enough that the
 * self-contained file rebuilds instantly, and a second output would be a
 * second thing to be stale.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const man  = JSON.parse(fs.readFileSync(path.join(ROOT, 'pca-studio/manifest.json'), 'utf8'));
const read = p => fs.readFileSync(path.join(ROOT, p), 'utf8');
/* keep the original casing — see the note in tools/build.js */
const esc  = s => s.replace(/<\/script>/gi, m => '<\\/' + m.slice(2));

const missing = [...man.css, ...man.js, man.body].filter(p => !fs.existsSync(path.join(ROOT, p)));
if (missing.length) {
  console.error('pca-studio/manifest.json lists files that do not exist:\n  ' + missing.join('\n  '));
  process.exit(1);
}
/* the orphan check that saved the sim twice: a module under pca-studio/src
   that nothing loads looks exactly like a module that works */
const listed = new Set([...man.css, ...man.js, man.body]);
const orphans = [];
(function walk(dir){
  for (const e of fs.readdirSync(dir, {withFileTypes:true})) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) walk(full);
    else if (/\.(js|css|html)$/.test(e.name)) {
      const rel = path.relative(ROOT, full).split(path.sep).join('/');
      if (!listed.has(rel)) orphans.push(rel);
    }
  }
})(path.join(ROOT, 'pca-studio/src'));
if (orphans.length) {
  console.error('BUILD FAILED — these files are under pca-studio/src/ but not in\n' +
    'pca-studio/manifest.json, so nothing loads them:\n  ' + orphans.join('\n  '));
  process.exit(1);
}

const out = '<!doctype html>\n<html lang="en">\n<head>\n'
  + '<meta charset="utf-8">\n'
  + '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
  + '<title>' + man.title + '</title>\n'
  + '<!-- GENERATED by tools/build-studio.js from pca-studio/manifest.json.\n'
  + '     Do not edit this file: edit the modules and run ./build.sh. -->\n'
  + '<style>\n' + man.css.map(read).join('\n') + '\n</style>\n'
  + '</head>\n'
  + read(man.body).replace(/\s*$/, '\n')
  + man.js.map(p => '<script>/* ' + p + ' */\n' + esc(read(p)) + '</script>').join('\n')
  + '\n</body>\n</html>\n';

fs.writeFileSync(path.join(ROOT, 'pca-studio/PCA-Studio.html'), out);
console.log('PCA-Studio.html   ' + (out.length / 1024).toFixed(0) + ' KB  (' +
  man.js.length + ' modules, ' + man.js.filter(p=>p.startsWith('src/')).length + ' shared with the sim)');
