/* sequences.h — generated by the R2-D2 Simulator v0.12.1 (PCA Studio)
   Source: PCA Studio — jerk diagnostic (6 channels, 4 sequences)
   Consumed by the MaestroPCA library (arduino/MaestroPCA).

   Wiring: channel i lives on PCA9685 board (i/16), pin (i%16).
     board 0 -> I2C address 0x40 (channels 0..5)
   Targets are QUARTER-MICROSECONDS (6000 = 1500 us), straight from
   the Maestro channel table — endpoints are YOUR calibration.
   Calibrate the PCA9685 oscillator (maestro.begin(<hz>)) or these
   values are only nominal on the wire. */
#pragma once
#include "MaestroPCA.h"

#define MPCA_CHANNELS  6
#define MPCA_SEQUENCES 4

/* releaseMs: stop pulsing this long after arriving — a parked panel
   then draws nothing and makes no noise. ONLY safe where the part
   rests in place on its own; a servo holding against gravity drops.
   0 = hold forever, which is a real Maestro's only behaviour. */
/*  board pin    min    max   home  speed accel  release  ease */
const MpcaChannelDef MPCA_CHANNEL_TABLE[MPCA_CHANNELS] PROGMEM = {
  {  0,   0,  4800,  7200,  6000,    5,    0,       0, MPCA_EASE_NONE      },   /* ch 0 spd 5 */
  {  0,   1,  4800,  7200,  6000,   10,    0,       0, MPCA_EASE_NONE      },   /* ch 1 spd 10 */
  {  0,   2,  4800,  7200,  6000,   20,    0,       0, MPCA_EASE_NONE      },   /* ch 2 spd 20 */
  {  0,   3,  4800,  7200,  6000,   40,    0,       0, MPCA_EASE_NONE      },   /* ch 3 spd 40 */
  {  0,   4,  4800,  7200,  6000,   80,    0,       0, MPCA_EASE_NONE      },   /* ch 4 spd 80 */
  {  0,   5,  4800,  7200,  6000,   40,   10,       0, MPCA_EASE_NONE      },   /* ch 5 spd 40 +accel */
};

/* Frame stride = 1 duration + 6 targets. 0 = channel not driven
   by that frame (the Maestro sequencer convention).
   Sequences on disjoint channels play AT THE SAME TIME; one that
   claims a channel another is using displaces it. MPCA_SEQ_LOOP
   repeats until stopped or displaced. */
static const uint16_t MPCA_SEQ0[] PROGMEM = {   /* 0 Ladder — every speed at once */
   6000, 4800, 4800, 4800, 4800, 4800, 4800,
   6000, 7200, 7200, 7200, 7200, 7200, 7200,
   6000, 4800, 4800, 4800, 4800, 4800, 4800,
   2500, 6000, 6000, 6000, 6000, 6000, 6000,
};
static const uint16_t MPCA_SEQ1[] PROGMEM = {   /* 1 Crawl — slowest channel only */
   6000, 4800, 0, 0, 0, 0, 0,
   6000, 7200, 0, 0, 0, 0, 0,
   6000, 4800, 0, 0, 0, 0, 0,
   2500, 6000, 0, 0, 0, 0, 0,
};
static const uint16_t MPCA_SEQ2[] PROGMEM = {   /* 2 Snap — fastest channel, six times */
    900, 0, 0, 0, 0, 4800, 0,
    900, 0, 0, 0, 0, 7200, 0,
    900, 0, 0, 0, 0, 4800, 0,
    900, 0, 0, 0, 0, 7200, 0,
    900, 0, 0, 0, 0, 4800, 0,
    900, 0, 0, 0, 0, 7200, 0,
    900, 0, 0, 0, 0, 4800, 0,
    900, 0, 0, 0, 0, 7200, 0,
    900, 0, 0, 0, 0, 4800, 0,
    900, 0, 0, 0, 0, 7200, 0,
    900, 0, 0, 0, 0, 4800, 0,
    900, 0, 0, 0, 0, 7200, 0,
   1200, 0, 0, 0, 0, 6000, 0,
};
static const uint16_t MPCA_SEQ3[] PROGMEM = {   /* 3 Hold centre — is it quiet when still? */
  20000, 6000, 6000, 6000, 6000, 6000, 6000,
};

const MpcaSeqDef MPCA_SEQ_TABLE[MPCA_SEQUENCES] PROGMEM = {
  { MPCA_SEQ0, 4, 0 },   /* 0: 0 Ladder — every speed at once */
  { MPCA_SEQ1, 4, 0 },   /* 1: 1 Crawl — slowest channel only */
  { MPCA_SEQ2, 13, 0 },   /* 2: 2 Snap — fastest channel, six times */
  { MPCA_SEQ3, 1, 0 },   /* 3: 3 Hold centre — is it quiet when still? */
};

#define MPCA_SLOT_0_LADDER_EVERY_SPEED_AT_ONCE 0
#define MPCA_SLOT_1_CRAWL_SLOWEST_CHANNEL_ONLY 1
#define MPCA_SLOT_2_SNAP_FASTEST_CHANNEL_SIX_TIMES 2
#define MPCA_SLOT_3_HOLD_CENTRE_IS_IT_QUIET_WHEN_STILL 3
